version: '2'  #设定版本
services:

  consul:
    image: consul:latest
    container_name: myconsul
    ports:
      - "8500:8500"
#    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1 -datacenter=dc1
    command: agent -server -bootstrap -ui -node=1 -client='0.0.0.0'
  seckilladmin:
    build: .
    container_name: sk-admin
    depends_on:
      - consul
    ports:
      - "9030:9030"