apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
        - args:
            - agent
            - -server
            - -bootstrap
            - -ui
            - -node=1
            - -client=0.0.0.0
          image: consul:latest
          name: secconsul
          ports:
            - containerPort: 8500
          resources: {}
      restartPolicy: Always
status: {}
