apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo1
  name: zoo1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zoo1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: zoo1
    spec:
      containers:
        - image: zookeeper:latest
          name: seczool
          ports:
            - containerPort: 2181
          resources: {}
      restartPolicy: Always
status: {}
