apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo1
  name: zoo1
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    - name: 2181-tcp
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zoo1
status:
  loadBalancer: {}
